assert.ok not is_array(undefined),  "undefined is considered array"
assert.ok not is_array(null),       "null is considered array"
assert.ok not is_array(true),       "true is considered array"
assert.ok not is_array(false),      "false is considered array"
assert.ok not is_array(0),          "0 is considered array"
assert.ok not is_array(-15),        "-15 is considered array"
assert.ok not is_array(3.14),       "3.14 is considered array"
assert.ok not is_array('foo'),      "'foo' is considered array"
assert.ok not is_array({}),         "{} is considered array"
assert.ok not is_array({foo: 1}),   "{foo: 1} is considered array"
assert.ok     is_array([]),         "[] is not recognized as an array"
assert.ok     is_array([1, 'foo']), "[1, 'foo'] is not recognized as an array"
